<?php
$atoken= $_GET["atoken"];
$buyerInfo = $_GET["buyerInfo"];
$buyerInfo = explode(",", $buyerInfo);
$payload =  "{
	\"intent\": \"CAPTURE\",
    \"payer\":{
        \"email_addres\":\"$buyerInfo[2]\",
        \"name\":{
            \"given_name\":\"$buyerInfo[0]\",
            \"surname\":\"$buyerInfo[1]\"
        }
    },
    \"purchase_units\": [
        {
            \"amount\": {
                \"breakdown\": {
                    \"item_total\": {
                        \"currency_code\": \"BRL\",
                        \"value\":\"$buyerInfo[9]\"
                    },
                    \"shipping\": {
                        \"currency_code\": \"BRL\",
                        \"value\":\"$buyerInfo[10]\"
                    },
					\"tax_total\":{
						\"currency_code\": \"BRL\",
						\"value\":\"0.00\"
					}
                },
                \"currency_code\": \"BRL\",
                \"value\":\"$buyerInfo[8]\"
            },
            \"items\": [
                {
                    \"category\": \"PHYSICAL_GOODS\",
                    \"description\": \"Size : 26\",
                    \"name\": \"Product 1\",
                    \"quantity\":\"$buyerInfo[11]\",
                    \"unit_amount\": {
                        \"currency_code\": \"BRL\",
                        \"value\": \"54.00\"
                    }
                },
                {
                    \"category\": \"PHYSICAL_GOODS\",
                    \"description\": \"Size: M\",
                    \"name\": \"Product 2\",
                    \"quantity\":\"$buyerInfo[12]\",
                    \"unit_amount\": {
                        \"currency_code\": \"BRL\",
                        \"value\": \"16.00\"
                    }
                }
            ],
            \"reference_id\": \"IdemptID\",
            \"shipping\": {
                \"address\": {
                    \"address_line_1\": \"$buyerInfo[7]\",
                    \"admin_area_1\":\"$buyerInfo[5]\",
					\"admin_area_2\": \"$buyerInfo[13]\",
                    \"country_code\":\"$buyerInfo[4]\",
                    \"postal_code\":\"$buyerInfo[6]\"
                },
				\"method\": \"Brasil Postal Service\"
            },
            \"soft_descriptor\": \"PYPL\"
        }
    ]
}";

// Create order
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v2/checkout/orders');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $payload);

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer ' . $atoken;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$result = json_decode($result);
$idOrder = $result->id;

if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
//echo $payload;
echo $idOrder;
?>