<?php // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

require("./Reference/aTokenCreate.php");

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api-m.sandbox.paypal.com/v1/billing-agreements/agreement-tokens');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt(
    $ch,
    CURLOPT_POSTFIELDS,
    "{  
    \"description\": \"Billing Agreement\",
      \"shipping_address\":  {
            \"line1\": \"1350 North First Street\",
                \"city\": \"San Jose\",
                    \"state\": \"CA\",
                        \"postal_code\": \"95112\",
                            \"country_code\": \"US\",
                                \"recipient_name\": \"John Doe\"  
                            },
                              \"payer\":  {
                                    \"payment_method\": \"PAYPAL\"  
                                },
                                  \"plan\":  {
                                        \"type\": \"MERCHANT_INITIATED_BILLING\",
                                            \"merchant_preferences\":    {
                                                      \"return_url\": \"https://example.com/return\",
                                                            \"cancel_url\": \"https://example.com/cancel\",
                                                                  \"notify_url\": \"https://example.com/notify\",
                                                                          \"accepted_pymt_type\": \"INSTANT\",
                                                                                \"skip_shipping_address\": false,
                                                                                      \"immutable_shipping_address\": true    
                                                                                    }
                                                                                  }
                                                                                }"
);

$headers = array();
$headers[] = 'Content-Type: application/json';
$headers[] = 'Authorization: Bearer ' . $atoken;
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$result = json_decode($result);
//print_r($result);
//print_r($result->token_id); //retornou token_id

return $result->token_id;
